### ISSUE TITLE
need to demonstrate data merging capability

### ISSUE THREAD

**Issue by jvandegriff** [hapi-server/client-python#35] opened 2020-12-15 17:58 UTC
as promised in the HAPI-client expansion proposal to HDEE, we would like to create a way to fuse multiple datasets. The datasets to merge could be from the same server, or from different servers.  

This ticket is about creating a capability in client code to to data merging on the client.  Note that you could also conceive of adding this code on a server and, with a proper API for specifying multiple datasets (or really specific parameters from multiple datasets), as well as a time merging strategy (interpolate to a single fine-grained cadence, or average everything to a uniform cadence, etc), you coudl create a data fusing HAPI server that reads from many other HAPI servers.

This issues is not about that, but just about demonstrating how easy it is in the client to take HAPI data and merge it with other HAPI data.  Even on the client, there are options.  The easiest way would be to fully read data from each dataset to be merged, and then do the merging once all the desired parameters from each dataset are already in hand (or really, in memory). Since HAPI is a streaming format, you could do a more sophisticated merge that reads from each server and does the fusing on the fly, so that you take full advantage of the streaming aspect of HAPI and would therefore be able to handle very larger requests without having to pull everything into memory.

For now, we should define a function that takes a list of data sources and a time range, and an averaging interval, and creates a single averaged dataset out of all the parameters in each source. The metadata also needs to be combined from each source. Collisions of parameter names also need to be avoided in the resulting merged product.

So the merge routine should take these objects:
  TimeRange
  averagingIntervalWidthInSeconds
  List of DataSources, each one having:
     hapiServer
     datasetId
     parameterList
and return a data object representing a single name space of all the parameters averaged on to the requested cadence.

**Comment by rweigel** [comment] 2020-12-15 21:14
We discussed three possibilities

1. Add simple documentation on how best to do merging - both Pandas and NumPy could be used. What are advantages/disadvantages of each?
2. Add native functionality to the HAPI client
3. A separate package that does this - especially in the context of the project on the heliopy data model (would be useful to create a repository so that I could link to it here)

I'd like to hear from @darrendezeeuw on this. I know that Kamodo does interpolation too.

Besides simple interpolation onto a common time grid, I think it should support re-gridding. Given a bin width, return averages of all non-fills in that bin. I'd use this before I used interpolation - basic time series interpolation usually does not make sense when gaps are much larger than its autocorrelation time constant.

@jbfaden could probably suggest other functions.

**Comment by jbfaden** [comment] 2020-12-15 21:27
I'm pretty sure it should be a separate package, or fairly independent from the server.  For example, we could develop a bunch of the code as a demonstration server which takes a configuration file containing the inputs you describe (hapiServers, datasetIds, parameterList, averagingIntervalWidthInSeconds, etc) and present a HAPI server itself.  Then it does matter what each input HAPI server is implemented as.  I think the ideal implementation is one which is easily installed.  Maybe that means it's Python or Node.  It's impressive how easily those are installed, but that limits who can do this.  Another thought is for me to look at the lightweight Java-servers. 

Let me know if there's another ticket on this, but we also need to consider average types--for angles you don't want to average 1 and 259 and get 180 (because it should be average type "angle" or "mod360").

**Comment by rweigel** [comment] 2020-12-15 22:29
@jbfaden did you mean "independent of the client"? We're talking about the Python client here.

**Comment by jbfaden** [comment] 2020-12-15 23:40
Seems like this should be a server-side thing, or maybe we could make this something that could work on either the server-side or the client-side.

**Comment by rweigel** [comment] 2020-12-16 15:36
We discussed this and decided it was out of scope for what was proposed. We also discussed the fact that a server-side code would be useful but there would be two complications 1. implementation would be a bit more complex and 2. data providers would be uncomfortable with it. In addition, we would want to first scope out the API for it, probably as an extension.

I'm guessing Autoplot could be used to quickly implement a server-side code that the generic server could call on the back-end.

**Comment by jbfaden** [comment] 2020-12-16 17:26
I've worked a bit in this direction--the problem is though HAPI servers are streaming, streaming within Autoplot is a newer thing and I'd need to remind myself if you can get a stream of data from a HAPI server.  It would be interesting to experiment with, for sure, but I'll do that outside the scope of this ticket.

**Comment by darrendezeeuw** [comment] 2020-12-16 19:08
I’m coming into the middle of this thread, so I’m not sure the original issue.  Kamodo does have interpolation, as each Kamodofied model needs to have and interpolator to “functionalize” the data, ie. Rho(x,y,z) for any x,y,z in the valid domain. With simpler data structures, we are just using scipy interpolating functions.  More complex models are requiring more complex interpolation.  However, Kamodo is not yet available as a service or API.  That is part of our long-term plan, but is not ready yet.  Kamodo is probably not the right tool to interpolate and re-bin data in a time series as a simpler python toolkit would suffice.

Darren.

**Comment by rweigel** [comment] 2022-06-28 15:02
This is done in https://github.com/hapi-server/tutorial-python and will eventually be a part of https://github.com/hapi-server/application-neuralnetwork-python

**Closed by rweigel** 2022-06-28 15:02 UTC
